### ISSUE TITLE
bug: CoreContainer is not rendering

### ISSUE THREAD

**Issue by samhere17** [wrappid/core#159]
### Describe the bug
CoreContainer is not rendering.
I have added the below code in one of my component and it is not rendering.
```javascript
<CoreContainer>hello</CoreContainer>
```

### To Reproduce
Use `<CoreContainer>hello</CoreContainer>` anywhere.

### Expected behavior
CoreContainer should render.

### Stack Trace
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CoreContainer`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `CoreContainer`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:296313:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:296334:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:285433:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:285483:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:288422:32)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:289259:9)
    at beginWork (http://localhost:3000/static/js/bundle.js:290487:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:275503:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:275547:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:275604:35)
```

**Comment by Edithmark42** [comment]
This issue was resolved in [Native-web](https://github.com/wrappid/native-web/pull/43) and [Native-mobile](https://github.com/wrappid/native-mobile/pull/47).

**Comment by techoneel** [comment]
resolved this issue
