### ISSUE TITLE
bug: CoreMultiTimeRangePicker error on field erase

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/core#269]
**Describe the bug**
CoreMultiTimeRangePicker error on complete field erase.

**To Reproduce**
Please check provided screenshot

**Expected behavior**
No error on complete field erasing. Refer provided screenshot.

**Stack Trace**
```
TypeError: Cannot read properties of null (reading 'format')
    at _handleChange (http://localhost:3000/static/js/bundle.js:112082:20)
    at onChange (http://localhost:3000/static/js/bundle.js:112100:7)
    at onChange (http://localhost:3000/static/js/bundle.js:150036:9)
    at http://localhost:3000/static/js/bundle.js:247459:5
    at Object.handleChange [as onChange] (http://localhost:3000/static/js/bundle.js:247183:5)
    at http://localhost:3000/static/js/bundle.js:362463:15
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:338904:30)
    at commitLayoutEffectOnFiber (http://localhost:3000/static/js/bundle.js:339004:21)
    at commitLayoutMountEffects_complete (http://localhost:3000/static/js/bundle.js:340203:13)
    at commitLayoutEffects_begin (http://localhost:3000/static/js/bundle.js:340192:11)


    at KeyboardDateInput (http://localhost:3000/static/js/bundle.js:245455:7)
    at DesktopWrapper (http://localhost:3000/static/js/bundle.js:246828:5)
    at DesktopTimePicker (http://localhost:3000/static/js/bundle.js:239986:98)
    at TimePicker (http://localhost:3000/static/js/bundle.js:243894:81)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at LocalizationProvider (http://localhost:3000/static/js/bundle.js:240330:81)
    at NativeTimePicker (http://localhost:3000/static/js/bundle.js:149997:5)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at http://localhost:3000/static/js/bundle.js:117093:53
    at CoreTimePicker (http://localhost:3000/static/js/bundle.js:114047:5)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeGrid (http://localhost:3000/static/js/bundle.js:150942:48)
    at CoreGrid (http://localhost:3000/static/js/bundle.js:117267:53)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at http://localhost:3000/static/js/bundle.js:117093:53
    at CoreMultiTimeRangePicker (http://localhost:3000/static/js/bundle.js:112048:5)
    at CoreFormInputs (http://localhost:3000/static/js/bundle.js:116181:5)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeGrid (http://localhost:3000/static/js/bundle.js:150942:48)
    at CoreGrid (http://localhost:3000/static/js/bundle.js:117267:53)
    at form
    at NativeFormContainer (http://localhost:3000/static/js/bundle.js:146394:73)
    at CoreFormContainer (http://localhost:3000/static/js/bundle.js:115651:94)
    at Formik (http://localhost:3000/static/js/bundle.js:256927:19)
    at CoreEditForm (http://localhost:3000/static/js/bundle.js:114437:35)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at http://localhost:3000/static/js/bundle.js:117093:53
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeGrid (http://localhost:3000/static/js/bundle.js:150942:48)
    at CoreGrid (http://localhost:3000/static/js/bundle.js:117267:53)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeGrid (http://localhost:3000/static/js/bundle.js:150942:48)
    at CoreGrid (http://localhost:3000/static/js/bundle.js:117267:53)
    at CoreForm (http://localhost:3000/static/js/bundle.js:114728:1)
    at ConnectFunction (http://localhost:3000/static/js/bundle.js:346197:114)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at CardContent (http://localhost:3000/static/js/bundle.js:185090:82)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeCardContent (http://localhost:3000/static/js/bundle.js:152753:95)
    at CoreCardContent (http://localhost:3000/static/js/bundle.js:121808:53)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Paper (http://localhost:3000/static/js/bundle.js:203248:83)
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Card (http://localhost:3000/static/js/bundle.js:184571:82)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeCard (http://localhost:3000/static/js/bundle.js:152570:166)
    at CoreCard (http://localhost:3000/static/js/bundle.js:121577:53)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Grid (http://localhost:3000/static/js/bundle.js:192406:87)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeGrid (http://localhost:3000/static/js/bundle.js:150942:48)
    at CoreGrid (http://localhost:3000/static/js/bundle.js:117267:53)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at http://localhost:3000/static/js/bundle.js:117093:53
    at main
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at NativeAppContainer (http://localhost:3000/static/js/bundle.js:150647:5)
    at LayoutManager (http://localhost:3000/static/js/bundle.js:129171:5)
    at div
    at http://localhost:3000/static/js/bundle.js:170993:66
    at Box (http://localhost:3000/static/js/bundle.js:229309:72)
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeBox
    at NativePageContainer (http://localhost:3000/static/js/bundle.js:151230:5)
    at RtlProvider (http://localhost:3000/static/js/bundle.js:227742:7)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:226550:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:228031:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:223790:14)
    at NativeThemeProvider (http://localhost:3000/static/js/bundle.js:159468:45)
    at CoreThemeProvider (http://localhost:3000/static/js/bundle.js:136772:53)
    at StylesProvider (http://localhost:3000/static/js/bundle.js:159856:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:129815:5)
    at PageContainer (http://localhost:3000/static/js/bundle.js:129594:48)
    at Routes (http://localhost:3000/static/js/bundle.js:349511:5)
    at CoreRoutes (http://localhost:3000/static/js/bundle.js:96816:35)
    at Router (http://localhost:3000/static/js/bundle.js:349451:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:348383:5)
    at NativeNavigation (http://localhost:3000/static/js/bundle.js:151857:5)
    at CoreNavigation (http://localhost:3000/static/js/bundle.js:120061:90)
    at div
    at O (http://localhost:3000/static/js/bundle.js:363821:8)
    at NativeAppDiv (http://localhost:3000/static/js/bundle.js:150719:85)
    at CoreAppDiv (http://localhost:3000/static/js/bundle.js:117010:53)
    at RtlProvider (http://localhost:3000/static/js/bundle.js:227742:7)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:226550:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:228031:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:223790:14)
    at NativeThemeProvider (http://localhost:3000/static/js/bundle.js:159468:45)
    at CoreThemeProvider (http://localhost:3000/static/js/bundle.js:136772:53)
    at CoreRoutesProvider (http://localhost:3000/static/js/bundle.js:130601:13)
    at CoreContextProvider (http://localhost:3000/static/js/bundle.js:130903:5)
    at StylesProvider (http://localhost:3000/static/js/bundle.js:159856:5)
    at PersistGate (http://localhost:3000/static/js/bundle.js:360545:5)
    at Provider (http://localhost:3000/static/js/bundle.js:345928:3)
    at CoreProvider (http://localhost:3000/static/js/bundle.js:131052:5)
    at WrappidSyncer (http://localhost:3000/static/js/bundle.js:160514:3)
    at CoreAppStrictWrapper (http://localhost:3000/static/js/bundle.js:96722:5)
    at CoreApp (http://localhost:3000/static/js/bundle.js:96623:5)
    at App
```
**Screenshots**
![errorCoreMultiTimeRangePicker](https://github.com/user-attachments/assets/a5aa5ba2-01f0-4adc-b217-fe75f18c7976)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40 (Workstation Edition) x86_64
 - Browser: Brave
 - Version: [Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**
N/A

**Comment by techoneel** [comment]
https://github.com/wrappid/core/blob/f14130ea6c275050d65dd20d47be6705297d8229/package/components/inputs/CoreMultiTimeRangePicker.js#L56

Solution:
`x[i][type] = v?.format("LLL");`

@anantakumarghosh solve and fix

**Comment by anantakumarghosh** [comment]
Closing as done.
